# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
np.diag([1,2,3,4] , -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [78]:
x=np.arange(64).reshape(8,8) 
print(x)

y=x[0:9, 0:9]
z=np.where(y>=0, '*', y)
z


[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]


array([['*', '*', '*', '*', '*', '*', '*', '*'],
       ['*', '*', '*', '*', '*', '*', '*', '*'],
       ['*', '*', '*', '*', '*', '*', '*', '*'],
       ['*', '*', '*', '*', '*', '*', '*', '*'],
       ['*', '*', '*', '*', '*', '*', '*', '*'],
       ['*', '*', '*', '*', '*', '*', '*', '*'],
       ['*', '*', '*', '*', '*', '*', '*', '*'],
       ['*', '*', '*', '*', '*', '*', '*', '*']], dtype='<U11')

# 4. Normalize a 5x5 random matrix

In [4]:

import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.54582499 0.56126891 0.50923327 0.51638027 0.47271819]
 [0.59207465 0.44448036 0.18148936 0.66660962 0.75010843]
 [0.71830731 0.81089213 0.72524233 0.25103223 0.83081252]
 [0.38707822 0.79581716 0.73915486 0.95430401 0.99992222]
 [0.96692284 0.84652328 0.9123233  0.56057421 0.6867933 ]]
After normalization:
[[0.44516252 0.46403263 0.40045303 0.40918556 0.35583718]
 [0.50167254 0.32133485 0.         0.59274289 0.69476569]
 [0.65590958 0.76903409 0.66438311 0.08497077 0.79337377]
 [0.2511982  0.75061478 0.6813821  0.94426151 1.        ]
 [0.95967979 0.81256992 0.89296749 0.46318382 0.61740427]]


# 5.  How to find common values between two arrays?

In [137]:
a=np.arange(10)
b=np.arange(6,15)
print(a)
print(b)
print("--------------------------------")
print(np.intersect1d(a, b))

[0 1 2 3 4 5 6 7 8 9]
[ 6  7  8  9 10 11 12 13 14]
--------------------------------
[6 7 8 9]


# 6.How to get the dates of yesterday, today and tomorrow?

In [5]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-08-01
Today:  2020-08-02
Tomorrow:  2020-08-03


# 7. Consider two random array A and B, check if they are equal

In [158]:
a=np.empty((3,3))
b=np.empty((3,3))
c=a==b
d=c.all()
print(d)

True


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [178]:
v=np.empty(10)
#print(v)
n=np.empty((10,10))
#print(n)
m=np.dot(n,v)
print(m,'\n')
print("--------------------------------------------------------------------",'\n')
#k=max(m)
m=np.where(m==max(m),0,m)
print(m)





[36.1316354  33.65931107 22.12537024 27.35651229 28.94264609 30.34385129
 44.22791356 17.84977996 23.90213348 29.86241938] 

-------------------------------------------------------------------- 

[36.1316354  33.65931107 22.12537024 27.35651229 28.94264609 30.34385129
  0.         17.84977996 23.90213348 29.86241938]


# 9. How to print all the values of an array?

In [172]:
l=np.empty(10)
for i in l:
    print(i)

0.7210204896729365
0.9846112374844651
0.470104823874279
0.07854594901461476
0.3253778367036344
0.17780947386140744
0.485157328431259
0.7391403524639768
0.7852101915166511
0.27884970311017665


# 10.Subtract the mean of each row of a matrix

In [7]:
import numpy as np
a = np.arange(12).reshape(3,4)
print(a)
print("---------------------------------------------")
b = a - a.mean(axis=1, keepdims = True)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
---------------------------------------------
[[-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [9]:
a = np.random.randint(1,8,8)
print(a)
print("-----------------------")
b = np.random.randint(a)
c = []
b.sort()
for i in b:
    if i not in c:
        c.append(i)

for j in c:
    a[j] += 1

print("Indexing vector:", b)
print("Result:",a)

[4 3 2 6 2 1 1 1]
-----------------------


TypeError: only size-1 arrays can be converted to Python scalars

# 12.How to get the diagonal of a dot product?

In [11]:
a = [[1,2],[3,4]]
b = [[1,2],[3,4]]
Z = np.diag(np.dot(a,b))
Z

array([ 7, 22])

# 13.How to find the most frequent value in an array?

In [12]:
x=np.array([1,2,3,3,4,5])
print(np.bincount(x).argmax())

3


# 14.How to get the n largest values of an array

In [15]:
n=np.empty(10)
print(n)
print("---------------------------")
print(max(n))

[6.23042070e-307 7.56587584e-307 1.37961302e-306 4.45055939e-308
 1.15711378e-306 6.23060065e-307 1.69115935e-306 1.60221072e-306
 8.34445138e-308 2.54643413e-312]
---
1.691159347915686e-306


# 15.How to create a record array from a regular array?

In [16]:
a=np.array(['car','bus','auto','taxi'])
b=np.array(['Red','oorange','yellow','black'])
result= np.core.records.fromarrays([a, b])
print(result[0])
print(result[1])
print(result[2])

('car', 'Red')
('bus', 'oorange')
('auto', 'yellow')
